{
	"version": 1717778536,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/kittybong-sheet0.png",
		"images/kittybed-sheet0.png",
		"images/gamingchairback-sheet0.png",
		"images/kittysprite-sheet0.png",
		"images/kittysprite-sheet1.png",
		"images/kittysprite-sheet2.png",
		"images/kittyroomcoloredfinal-sheet0.png",
		"images/computer-sheet0.png",
		"images/window-sheet0.png",
		"images/plant-sheet0.png",
		"images/blackball-sheet0.png",
		"images/hellopink-sheet0.png",
		"images/instructionsline-sheet0.png",
		"images/instructionsline2-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}